spring.datasource.url=jdbc:postgresql://localhost:5432/finance
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zaibatsusquad@gmail.com
spring.mail.password=ygtk ymzr ahnj bgrh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret-key=679da1a2eb1c5941a82b57bf51129b16d3d0d5b1a49fb577cc12c44a4b55607b68e16686fda604225f823509efa101471162cc1253d4fe4926def69d990a29c7
jwt.expiration-time=36000000