spring.datasource.url=jdbc:postgresql://localhost:5432/finance
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zaibatsusquad@gmail.com
spring.mail.password=ygtk ymzr ahnj bgrh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true